version: "3.9"
services:
  whisper:
    image: ${WHISPER_IMAGE:-ghcr.io/sushikitchen/whisper-gpu:placeholder}
    container_name: whisper-gpu
    restart: unless-stopped
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-medium}
    ports:
      - "9001:9001"
    volumes:
      - ${WHISPER_CACHE_DIR:-./data/whisper/cache}:/root/.cache
      - ${WHISPER_AUDIO_DIR:-./data/whisper/audio}:/audio
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
