global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'n8n'
    metrics_path: /
    static_configs:
      - targets: ['n8n:5678']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
