name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write   # needed for SARIF uploads

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ---- Python lane (your app/) ----
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install ruff
      - run: ruff check .

  typecheck:
    name: Mypy Type Check
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install mypy and deps
        run: |
          pip install mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run mypy (skip if no app/)
        run: |
          if [ -d app ]; then mypy app; else echo "No app/ dir; skipping mypy."; fi

  tests:
    name: Pytest
    runs-on: ubuntu-latest
    needs: [typecheck]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Ensure tests dir exists (placeholder)
        run: |
          mkdir -p tests
          [ -f tests/test_placeholder.py ] || echo "def test_placeholder(): assert True" > tests/test_placeholder.py
      - name: Run tests
        run: pytest -q

  # ---- Node/docs lane (schema, compose, links, Trivy) ----
  quality:
    name: Quality (schema, compose, links, Trivy)
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: |
          npm i -g pnpm
          pnpm -w install

      # Make these blocking to enforce quality. If you prefer advisory, add "|| true".
      - name: Lint & style
        run: |
          pnpm -w format:check
          pnpm -w lint

      - name: Schema validate
        run: pnpm -w validate:schema

      - name: Compose validate
        run: docker compose config

      - name: Link check (advisory until tuned)
        run: pnpm -w check:links || true

      - name: Trivy scan (advisory)
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy.sarif

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy.sarif
